# Generated by Django 5.2.1 on 2025-05-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('idDirector', models.IntegerField()),
                ('imdb', models.IntegerField()),
                ('idCategoria', models.IntegerField()),
                ('caratula', models.IntegerField()),
                ('resenia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActorPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idActor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCine.actor')),
                ('idPelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCine.pelicula')),
            ],
        ),
    ]
