# Generated by Django 5.2.1 on 2025-05-12 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='caratula',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCine.categoria'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idDirector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCine.director'),
        ),
    ]
