# Generated by Django 5.2.1 on 2025-05-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0002_alter_pelicula_caratula_alter_pelicula_idcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='caratula',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imdb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='resenia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
