# Generated by Django 5.2.1 on 2025-05-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0003_alter_pelicula_caratula_alter_pelicula_imdb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='ordenNetflix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
