# Generated by Django 5.2.1 on 2025-05-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0004_pelicula_ordennetflix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='actores',
            field=models.ManyToManyField(related_name='peliculas', through='AppCine.ActorPelicula', to='AppCine.actor'),
        ),
    ]
