# Generated by Django 5.2.1 on 2025-06-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0005_pelicula_actores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imdb',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
