# Generated by Django 5.2.1 on 2025-06-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0006_alter_pelicula_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imdb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
